services:
  nginx:
    image: dhi/nginx:1-debian12

  healthcheck:
    image: dhi/busybox:1-alpine3.21
    command: ["sleep", "infinity"]
    healthcheck:
      test: wget -O - http://nginx:8080
      timeout: 10s
      retries: 3
      start_period: 2s
      start_interval: 1s

  test:
    image: dhi/curl:7-debian12 
    command: ["http://nginx:8080"]
    depends_on:
      healthcheck:
        condition: service_healthy
