FROM dhi/node:20-dev AS build

WORKDIR /home/node/app

ADD package.json .

RUN yarn

# -----

FROM dhi/node:20

WORKDIR /home/node/app

COPY --from=build /home/node/app .

ADD index.js .

EXPOSE 3000

CMD ["index.js"]
